### PR TITLE
add lang cs

### PR DESCRIPTION
**Pull request by CFenner**

### CODE REVIEW

**Comment by CFenner** [comment]
@zdeneksofr can you do the translation for the values in english?

**Comment by zdeneksofr** [comment]
@CFenner values of what? there are just numbers, or not?

**Comment by CFenner** [comment]
@zdeneksofr great, can you check again? The values for "trend" "radio signal" and "WiFi" are ok?

**Comment by zdeneksofr** [comment]
@CFenner yes, these words we usually use the same

**Comment by CFenner** [comment]
@zdeneksofr ok, then it's now in and you can use it in the standard. Thanks!

**Comment by zdeneksofr** [comment]
great job, thx

**Comment by CFenner** [comment]
@all-contributors please add @zdeneksofr for translation

**Pull request merged**
